---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
spec:
  project: kube-do
  source:
    repoURL: https://github.com/helm/charts.git
    path: stable/external-dns
    # https://github.com/argoproj/argo-cd/issues/1786
    helm:
      parameters:
        - name: provider
          value: digitalocean
        - name: digitalocean.apiToken
          #value: $(DIGITAL_OCEAN_TOKEN)
          value: {{ externalDns.digitalOceanToken }}
        - name: domainFilters
          #value: $(EXTERNAL_DNS_DOMAIN)
          value: {{ externalDns.domain }}
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-do
