---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
spec:
  project: kube-do-project
  source:
    repoURL: https://github.com/helm/charts.git
    path: stable/external-dns
    # version 1.7.10 - last commit before https://github.com/helm/charts/commit/19ae0b211eb291fd7e09949deb0784f44698b46e
    # FIXME https://github.com/argoproj/argo-cd/issues/1145
    targetRevision: ef5879ff5003632e13c23c78c0b04367411a03da
    helm:
      parameters:
        - name: provider
          value: digitalocean
        - name: digitalocean.apiToken
          value: {{ .Values.digitalOceanToken }}
        - name: rbac.create
          value: "true"
        - name: externalTrafficPolicy
          value: Local
        #- name: domainFilters[0]
        #  value: {{ .Values.domain }}
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-do
