---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ambassador
spec:
  project: ambassador
  source:
    repoURL: https://github.com/helm/charts.git
    path: stable/ambassador
    helm:
      parameters:
        - name: replicaCount
          value: "1"
        - name: service.annotations.external-dns\.alpha\.kubernetes\.io/hostname
          # wildcard dns record: see kube-do/external-dns for domain whitelisting
          value: "*.{{ .Values.domain }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: ambassador
