---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mobile-carrier-bot
spec:
  project: bot
  source:
    repoURL: https://github.com/niqdev/mobile-carrier-bot.git
    path: charts/app
    # FIXME add service.annotations to chart
    #helm:
    #  parameters:
    #    - name: service.annotations.external-dns\.alpha\.kubernetes\.io/hostname
    #      value: bot.{{ .Values.domain }}
  destination:
    server: https://kubernetes.default.svc
    namespace: bot
