---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: ambassador-mapping
spec:
  host: ambassador.{{ .Values.host }}
  prefix: /
  rewrite: /ambassador/v0/diag/
  service: ambassador-admins.ambassador:8877
